### ISSUE TITLE
Response closed without headers

### ISSUE THREAD

**Issue by VasilUrda** [improbable-eng/grpc-web#784] opened 2020-10-12 04:34 UTC
I am going to use `grpc-web` in react native and I used `grpc-web-react-native-transport`.

now I am getting this weird error. Does anyone know why?
![image](https://user-images.githubusercontent.com/33361100/95705602-2bce7100-0c87-11eb-91e4-3bae2719cbe8.png)

**Comment by johanbrandhorst** [comment] 2020-10-12 13:44
Dupe of https://github.com/improbable-eng/grpc-web/issues/690. This is a generic error seen when there's a network connection issue. Don't think there's anything you can do with it.

**Closed by johanbrandhorst** 2020-10-12 13:44 UTC

**Comment by MarcusLongmuir** [comment] 2020-10-12 13:48
Only thing I'll add is that without additional info it's hard to say, but are you definitely using a grpc-web proxy in front of your gRPC server? If not then the client would consistently (rather than just intermittently) complain about lacking the headers.

**Comment by forconz** [comment] 2021-09-10 15:10
The @improbable-eng/grpc-web client also supports Node.js
I use the @improbable-eng/grpc-web client in a node.js environment with Typescript, 
I had include dom in the "lib" Array in my tsconfig.json
```
{
    "compilerOptions": {
      "alwaysStrict": true,
      "sourceMap": true,
      "declaration": true,
      "declarationDir": "lib",
      "target": "es5",
      "removeComments": true,
      "noImplicitReturns": true,
      "noImplicitAny": true,
      "noUnusedLocals": true,
      "noUnusedParameters": true,
      "strictNullChecks": true,
      "stripInternal": true,
      "noFallthroughCasesInSwitch": true,
      "outDir": "lib",
      "noEmitOnError": true,
      "lib": ["DOM"]
    },
    "types": [
      "node"
    ],
    "include": [
      "src"
    ],
    "exclude": [
      "node_modules"
    ]
  }
```

import {grpc} from "@improbable-eng/grpc-web";
import { NodeHttpTransport } from '@improbable-eng/grpc-web-node-http-transport';
import {PadBotGrpcService} from './grpc/wechat_pb_service'
import { TestKeywordRequest } from './grpc/wechat_pb';

const main = async () => {
  const request = new TestKeywordRequest();
  console.log(`[getTestKeyword] Request: ${JSON.stringify(request.toObject())}`);

grpc.unary(PadBotGrpcService.GetTestKeyword, {
  request: request,
  transport: NodeHttpTransport(),
  host: 'https://localhost:8080',
  onEnd: res => {
    const { status, statusMessage, headers, message, trailers } = res;
    console.log(`[getTestKeyword] res: ${res}`);
    console.log(`[getTestKeyword] status: ${status}`);
    console.log(`[getTestKeyword] statusMessage: ${statusMessage}`);
    console.log(`[getTestKeyword] headers: ${headers}`);
    console.log(`[getTestKeyword] message: ${message}`);
    console.log(`[getTestKeyword] trailers: ${trailers}`);
    if (status === grpc.Code.OK && message) {
      console.log("all ok. got book: ", message.toObject());
    }
  }
});
}

console.log("call main(); ");
main();


PS D:\Projects\Test\helloworld> npm run demo

> grpc-web-simple-example@0.1.0 demo
> .\node_modules\.bin\ts-node .\src\main.ts

call main(); 
[getTestKeyword] Request: {}
[getTestKeyword] res: [object Object]
[getTestKeyword] status: 2
[getTestKeyword] statusMessage: Response closed without headers
[getTestKeyword] headers: [object Object]
[getTestKeyword] message: null
[getTestKeyword] trailers: [object Object]


**Response closed without headers**
How to resolve it?

**Comment by forconz** [comment] 2021-09-10 15:21
.\grpcwebproxy-v0.14.1-win64.exe --backend_addr=localhost:44392 --run_tls_server=false --allow_all_origins

I run grpc-web proxy in front of my gRPC server

PS D:\Projects\Test\helloworld> .\grpcwebproxy-v0.14.1-win64.exe --backend_addr=localhost:44392 --run_tls_server=false --allow_all_origins
time="2021-09-10T23:16:29+08:00" level=info msg="[core] parsed scheme: \"\"" system=system
time="2021-09-10T23:16:29+08:00" level=info msg="[core] scheme \"\" not registered, fallback to default scheme" system=system
time="2021-09-10T23:16:29+08:00" level=info msg="[core] ccResolverWrapper: sending update to cc: {[{localhost:44392  <nil> 0 <nil>}] <nil> <nil>}" system=system
time="2021-09-10T23:16:29+08:00" level=info msg="[core] ClientConn switching balancer to \"pick_first\"" system=system
time="2021-09-10T23:16:29+08:00" level=info msg="[core] Channel switches to new LB policy \"pick_first\"" system=system
time="2021-09-10T23:16:29+08:00" level=info msg="[core] Subchannel Connectivity change to CONNECTING" system=system
time="2021-09-10T23:16:29+08:00" level=info msg="[core] Channel Connectivity change to CONNECTING" system=system
time="2021-09-10T23:16:29+08:00" level=info msg="[core] Subchannel picks a new address \"localhost:44392\" to connect" system=system
time="2021-09-10T23:16:29+08:00" level=info msg="listening for http on: [::]:8080"
time="2021-09-10T23:16:29+08:00" level=info msg="[core] Subchannel Connectivity change to TRANSIENT_FAILURE" system=system
time="2021-09-10T23:16:29+08:00" level=info msg="[core] Channel Connectivity change to TRANSIENT_FAILURE" system=system
time="2021-09-10T23:16:30+08:00" level=info msg="[core] Subchannel Connectivity change to CONNECTING" system=system
time="2021-09-10T23:16:30+08:00" level=info msg="[core] Subchannel picks a new address \"localhost:44392\" to connect" system=system
time="2021-09-10T23:16:30+08:00" level=info msg="[core] Channel Connectivity change to CONNECTING" system=system
time="2021-09-10T23:16:30+08:00" level=info msg="[core] Subchannel Connectivity change to TRANSIENT_FAILURE" system=system
time="2021-09-10T23:16:30+08:00" level=info msg="[core] Channel Connectivity change to TRANSIENT_FAILURE" system=system
time="2021-09-10T23:16:32+08:00" level=info msg="[core] Subchannel Connectivity change to CONNECTING" system=system
time="2021-09-10T23:16:32+08:00" level=info msg="[core] Subchannel picks a new address \"localhost:44392\" to connect" system=system
time="2021-09-10T23:16:32+08:00" level=info msg="[core] Channel Connectivity change to CONNECTING" system=system
time="2021-09-10T23:16:32+08:00" level=info msg="[core] Subchannel Connectivity change to TRANSIENT_FAILURE" system=system
time="2021-09-10T23:16:32+08:00" level=info msg="[core] Channel Connectivity change to TRANSIENT_FAILURE" system=system
time="2021-09-10T23:16:34+08:00" level=info msg="[core] Subchannel Connectivity change to CONNECTING" system=system
time="2021-09-10T23:16:34+08:00" level=info msg="[core] Subchannel picks a new address \"localhost:44392\" to connect" system=system
time="2021-09-10T23:16:34+08:00" level=info msg="[core] Channel Connectivity change to CONNECTING" system=system
time="2021-09-10T23:16:34+08:00" level=info msg="[core] Subchannel Connectivity change to TRANSIENT_FAILURE" system=system
time="2021-09-10T23:16:34+08:00" level=info msg="[core] Channel Connectivity change to TRANSIENT_FAILURE" system=system
time="2021-09-10T23:16:38+08:00" level=info msg="[core] Subchannel Connectivity change to CONNECTING" system=system
time="2021-09-10T23:16:38+08:00" level=info msg="[core] Subchannel picks a new address \"localhost:44392\" to connect" system=system
time="2021-09-10T23:16:38+08:00" level=info msg="[core] Channel Connectivity change to CONNECTING" system=system
time="2021-09-10T23:16:38+08:00" level=info msg="[core] Subchannel Connectivity change to TRANSIENT_FAILURE" system=system
time="2021-09-10T23:16:38+08:00" level=info msg="[core] Channel Connectivity change to TRANSIENT_FAILURE" system=system
time="2021-09-10T23:16:45+08:00" level=info msg="[core] Subchannel Connectivity change to CONNECTING" system=system
time="2021-09-10T23:16:45+08:00" level=info msg="[core] Subchannel picks a new address \"localhost:44392\" to connect" system=system
time="2021-09-10T23:16:45+08:00" level=info msg="[core] Channel Connectivity change to CONNECTING" system=system
time="2021-09-10T23:16:45+08:00" level=info msg="[core] Subchannel Connectivity change to TRANSIENT_FAILURE" system=system
time="2021-09-10T23:16:45+08:00" level=info msg="[core] Channel Connectivity change to TRANSIENT_FAILURE" system=system
time="2021-09-10T23:16:56+08:00" level=info msg="[core] Subchannel Connectivity change to CONNECTING" system=system
time="2021-09-10T23:16:56+08:00" level=info msg="[core] Subchannel picks a new address \"localhost:44392\" to connect" system=system
time="2021-09-10T23:16:56+08:00" level=info msg="[core] Channel Connectivity change to CONNECTING" system=system
time="2021-09-10T23:16:56+08:00" level=warning msg="[core] grpc: addrConn.createTransport failed to connect to {localhost:44392 localhost:44392 <nil> 0 <nil>}. Err: write tcp [::1]:1238->[::1]:44392: wsasend: An existing connection was forcibly closed by the remote host.. Reconnecting..." system=system
time="2021-09-10T23:16:56+08:00" level=info msg="[core] Subchannel Connectivity change to TRANSIENT_FAILURE" system=system
time="2021-09-10T23:16:56+08:00" level=info msg="[core] Channel Connectivity change to TRANSIENT_FAILURE" system=system
time="2021-09-10T23:17:11+08:00" level=info msg="[core] Subchannel Connectivity change to CONNECTING" system=system
time="2021-09-10T23:17:11+08:00" level=info msg="[core] Subchannel picks a new address \"localhost:44392\" to connect" system=system
time="2021-09-10T23:17:11+08:00" level=info msg="[core] Channel Connectivity change to CONNECTING" system=system
time="2021-09-10T23:17:11+08:00" level=info msg="[core] Subchannel Connectivity change to TRANSIENT_FAILURE" system=system
time="2021-09-10T23:17:11+08:00" level=info msg="[core] Channel Connectivity change to TRANSIENT_FAILURE" system=system
time="2021-09-10T23:17:40+08:00" level=info msg="[core] Subchannel Connectivity change to CONNECTING" system=system
time="2021-09-10T23:17:40+08:00" level=info msg="[core] Subchannel picks a new address \"localhost:44392\" to connect" system=system
time="2021-09-10T23:17:40+08:00" level=info msg="[core] Channel Connectivity change to CONNECTING" system=system
time="2021-09-10T23:17:40+08:00" level=info msg="[core] Subchannel Connectivity change to TRANSIENT_FAILURE" system=system
time="2021-09-10T23:17:40+08:00" level=info msg="[core] Channel Connectivity change to TRANSIENT_FAILURE" system=system
time="2021-09-10T23:18:22+08:00" level=info msg="[core] Subchannel Connectivity change to CONNECTING" system=system
time="2021-09-10T23:18:22+08:00" level=info msg="[core] Subchannel picks a new address \"localhost:44392\" to connect" system=system
time="2021-09-10T23:18:22+08:00" level=info msg="[core] Channel Connectivity change to CONNECTING" system=system
time="2021-09-10T23:18:22+08:00" level=info msg="[core] Subchannel Connectivity change to TRANSIENT_FAILURE" system=system
time="2021-09-10T23:18:22+08:00" level=info msg="[core] Channel Connectivity change to TRANSIENT_FAILURE" system=system
time="2021-09-10T23:19:19+08:00" level=info msg="[core] Subchannel Connectivity change to CONNECTING" system=system
time="2021-09-10T23:20:21+08:00" level=info msg="[core] Channel Connectivity change to CONNECTING" system=system
time="2021-09-10T23:20:21+08:00" level=info msg="[core] Subchannel picks a new address \"localhost:44392\" to connect" system=system
time="2021-09-10T23:20:21+08:00" level=info msg="[core] Subchannel Connectivity change to TRANSIENT_FAILURE" system=system
time="2021-09-10T23:20:21+08:00" level=info msg="[core] Channel Connectivity change to TRANSIENT_FAILURE" system=system
