### ISSUE TITLE
cannot find package "google.golang.org/grpc/transport"

### ISSUE THREAD

**Issue by laSinteZ** [improbable-eng/grpc-web#216] opened 2018-07-12 09:59 UTC
Greetings! I am trying to start a `grpcwebproxy`, but when I try `go get -u github.com/improbable-eng/grpc-web/go/grpcwebproxy` i get:

```
root@f1b33891b086:/# go get -u github.com/improbable-eng/grpc-web/go/grpcwebproxy
package google.golang.org/grpc/transport: cannot find package "google.golang.org/grpc/transport" in any of:
	/usr/lib/go-1.10/src/google.golang.org/grpc/transport (from $GOROOT)
	/root/go/src/google.golang.org/grpc/transport (from $GOPATH)
```

I have the same result at MacOS and in `ubuntu:latest` docker image (so I guess it will be the minimum reproduction).

<details>
  <summary>Full log with <code>go get -u -v github.com/improbable-eng/grpc-web/go/grpcwebproxy</code>
</summary>
<code>
root@f1b33891b086:/# go get -u -v github.com/improbable-eng/grpc-web/go/grpcwebproxy
github.com/improbable-eng/grpc-web (download)
github.com/grpc-ecosystem/go-grpc-middleware (download)
Fetching https://golang.org/x/net/context?go-get=1
Parsing meta tags from https://golang.org/x/net/context?go-get=1 (status code 200)
get "golang.org/x/net/context": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/context?go-get=1
get "golang.org/x/net/context": verifying non-authoritative meta tag
Fetching https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
golang.org/x/net (download)
Fetching https://google.golang.org/grpc?go-get=1
Parsing meta tags from https://google.golang.org/grpc?go-get=1 (status code 200)
get "google.golang.org/grpc": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc?go-get=1
google.golang.org/grpc (download)
Fetching https://golang.org/x/net/http2?go-get=1
Parsing meta tags from https://golang.org/x/net/http2?go-get=1 (status code 200)
get "golang.org/x/net/http2": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/http2?go-get=1
get "golang.org/x/net/http2": verifying non-authoritative meta tag
Fetching https://golang.org/x/net/http/httpguts?go-get=1
Parsing meta tags from https://golang.org/x/net/http/httpguts?go-get=1 (status code 200)
get "golang.org/x/net/http/httpguts": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/http/httpguts?go-get=1
get "golang.org/x/net/http/httpguts": verifying non-authoritative meta tag
Fetching https://golang.org/x/net/idna?go-get=1
Parsing meta tags from https://golang.org/x/net/idna?go-get=1 (status code 200)
get "golang.org/x/net/idna": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/idna?go-get=1
get "golang.org/x/net/idna": verifying non-authoritative meta tag
Fetching https://golang.org/x/text/secure/bidirule?go-get=1
Parsing meta tags from https://golang.org/x/text/secure/bidirule?go-get=1 (status code 200)
get "golang.org/x/text/secure/bidirule": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/secure/bidirule?go-get=1
get "golang.org/x/text/secure/bidirule": verifying non-authoritative meta tag
Fetching https://golang.org/x/text?go-get=1
Parsing meta tags from https://golang.org/x/text?go-get=1 (status code 200)
golang.org/x/text (download)
Fetching https://golang.org/x/text/transform?go-get=1
Parsing meta tags from https://golang.org/x/text/transform?go-get=1 (status code 200)
get "golang.org/x/text/transform": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/transform?go-get=1
get "golang.org/x/text/transform": verifying non-authoritative meta tag
Fetching https://golang.org/x/text/unicode/bidi?go-get=1
Parsing meta tags from https://golang.org/x/text/unicode/bidi?go-get=1 (status code 200)
get "golang.org/x/text/unicode/bidi": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/unicode/bidi?go-get=1
get "golang.org/x/text/unicode/bidi": verifying non-authoritative meta tag
Fetching https://golang.org/x/text/unicode/norm?go-get=1
Parsing meta tags from https://golang.org/x/text/unicode/norm?go-get=1 (status code 200)
get "golang.org/x/text/unicode/norm": found meta tag get.metaImport{Prefix:"golang.org/x/text", VCS:"git", RepoRoot:"https://go.googlesource.com/text"} at https://golang.org/x/text/unicode/norm?go-get=1
get "golang.org/x/text/unicode/norm": verifying non-authoritative meta tag
Fetching https://golang.org/x/net/http2/hpack?go-get=1
Parsing meta tags from https://golang.org/x/net/http2/hpack?go-get=1 (status code 200)
get "golang.org/x/net/http2/hpack": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/http2/hpack?go-get=1
get "golang.org/x/net/http2/hpack": verifying non-authoritative meta tag
Fetching https://golang.org/x/net/trace?go-get=1
Parsing meta tags from https://golang.org/x/net/trace?go-get=1 (status code 200)
get "golang.org/x/net/trace": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/trace?go-get=1
get "golang.org/x/net/trace": verifying non-authoritative meta tag
Fetching https://golang.org/x/net/internal/timeseries?go-get=1
Parsing meta tags from https://golang.org/x/net/internal/timeseries?go-get=1 (status code 200)
get "golang.org/x/net/internal/timeseries": found meta tag get.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/internal/timeseries?go-get=1
get "golang.org/x/net/internal/timeseries": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/balancer?go-get=1
Parsing meta tags from https://google.golang.org/grpc/balancer?go-get=1 (status code 200)
get "google.golang.org/grpc/balancer": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/balancer?go-get=1
get "google.golang.org/grpc/balancer": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc?go-get=1
Parsing meta tags from https://google.golang.org/grpc?go-get=1 (status code 200)
Fetching https://google.golang.org/grpc/connectivity?go-get=1
Parsing meta tags from https://google.golang.org/grpc/connectivity?go-get=1 (status code 200)
get "google.golang.org/grpc/connectivity": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/connectivity?go-get=1
get "google.golang.org/grpc/connectivity": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/grpclog?go-get=1
Parsing meta tags from https://google.golang.org/grpc/grpclog?go-get=1 (status code 200)
get "google.golang.org/grpc/grpclog": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/grpclog?go-get=1
get "google.golang.org/grpc/grpclog": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/credentials?go-get=1
Parsing meta tags from https://google.golang.org/grpc/credentials?go-get=1 (status code 200)
get "google.golang.org/grpc/credentials": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/credentials?go-get=1
get "google.golang.org/grpc/credentials": verifying non-authoritative meta tag
github.com/golang/protobuf (download)
Fetching https://google.golang.org/grpc/resolver?go-get=1
Parsing meta tags from https://google.golang.org/grpc/resolver?go-get=1 (status code 200)
get "google.golang.org/grpc/resolver": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/resolver?go-get=1
get "google.golang.org/grpc/resolver": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/balancer/roundrobin?go-get=1
Parsing meta tags from https://google.golang.org/grpc/balancer/roundrobin?go-get=1 (status code 200)
get "google.golang.org/grpc/balancer/roundrobin": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/balancer/roundrobin?go-get=1
get "google.golang.org/grpc/balancer/roundrobin": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/balancer/base?go-get=1
Parsing meta tags from https://google.golang.org/grpc/balancer/base?go-get=1 (status code 200)
get "google.golang.org/grpc/balancer/base": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/balancer/base?go-get=1
get "google.golang.org/grpc/balancer/base": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/codes?go-get=1
Parsing meta tags from https://google.golang.org/grpc/codes?go-get=1 (status code 200)
get "google.golang.org/grpc/codes": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/codes?go-get=1
get "google.golang.org/grpc/codes": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/encoding?go-get=1
Parsing meta tags from https://google.golang.org/grpc/encoding?go-get=1 (status code 200)
get "google.golang.org/grpc/encoding": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/encoding?go-get=1
get "google.golang.org/grpc/encoding": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/encoding/proto?go-get=1
Parsing meta tags from https://google.golang.org/grpc/encoding/proto?go-get=1 (status code 200)
get "google.golang.org/grpc/encoding/proto": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/encoding/proto?go-get=1
get "google.golang.org/grpc/encoding/proto": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/internal?go-get=1
Parsing meta tags from https://google.golang.org/grpc/internal?go-get=1 (status code 200)
get "google.golang.org/grpc/internal": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/internal?go-get=1
get "google.golang.org/grpc/internal": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/internal/backoff?go-get=1
Parsing meta tags from https://google.golang.org/grpc/internal/backoff?go-get=1 (status code 200)
get "google.golang.org/grpc/internal/backoff": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/internal/backoff?go-get=1
get "google.golang.org/grpc/internal/backoff": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/internal/grpcrand?go-get=1
Parsing meta tags from https://google.golang.org/grpc/internal/grpcrand?go-get=1 (status code 200)
get "google.golang.org/grpc/internal/grpcrand": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/internal/grpcrand?go-get=1
get "google.golang.org/grpc/internal/grpcrand": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/internal/channelz?go-get=1
Parsing meta tags from https://google.golang.org/grpc/internal/channelz?go-get=1 (status code 200)
get "google.golang.org/grpc/internal/channelz": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/internal/channelz?go-get=1
get "google.golang.org/grpc/internal/channelz": verifying non-authoritative meta tag
Fetching https://golang.org/x/sys/unix?go-get=1
Parsing meta tags from https://golang.org/x/sys/unix?go-get=1 (status code 200)
get "golang.org/x/sys/unix": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at https://golang.org/x/sys/unix?go-get=1
get "golang.org/x/sys/unix": verifying non-authoritative meta tag
Fetching https://golang.org/x/sys?go-get=1
Parsing meta tags from https://golang.org/x/sys?go-get=1 (status code 200)
golang.org/x/sys (download)
Fetching https://google.golang.org/grpc/internal/envconfig?go-get=1
Parsing meta tags from https://google.golang.org/grpc/internal/envconfig?go-get=1 (status code 200)
get "google.golang.org/grpc/internal/envconfig": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/internal/envconfig?go-get=1
get "google.golang.org/grpc/internal/envconfig": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/internal/transport?go-get=1
Parsing meta tags from https://google.golang.org/grpc/internal/transport?go-get=1 (status code 200)
get "google.golang.org/grpc/internal/transport": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/internal/transport?go-get=1
get "google.golang.org/grpc/internal/transport": verifying non-authoritative meta tag
Fetching https://google.golang.org/genproto/googleapis/rpc/status?go-get=1
Parsing meta tags from https://google.golang.org/genproto/googleapis/rpc/status?go-get=1 (status code 200)
get "google.golang.org/genproto/googleapis/rpc/status": found meta tag get.metaImport{Prefix:"google.golang.org/genproto", VCS:"git", RepoRoot:"https://github.com/google/go-genproto"} at https://google.golang.org/genproto/googleapis/rpc/status?go-get=1
get "google.golang.org/genproto/googleapis/rpc/status": verifying non-authoritative meta tag
Fetching https://google.golang.org/genproto?go-get=1
Parsing meta tags from https://google.golang.org/genproto?go-get=1 (status code 200)
google.golang.org/genproto (download)
Fetching https://google.golang.org/grpc/keepalive?go-get=1
Parsing meta tags from https://google.golang.org/grpc/keepalive?go-get=1 (status code 200)
get "google.golang.org/grpc/keepalive": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/keepalive?go-get=1
get "google.golang.org/grpc/keepalive": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/metadata?go-get=1
Parsing meta tags from https://google.golang.org/grpc/metadata?go-get=1 (status code 200)
get "google.golang.org/grpc/metadata": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/metadata?go-get=1
get "google.golang.org/grpc/metadata": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/peer?go-get=1
Parsing meta tags from https://google.golang.org/grpc/peer?go-get=1 (status code 200)
get "google.golang.org/grpc/peer": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/peer?go-get=1
get "google.golang.org/grpc/peer": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/stats?go-get=1
Parsing meta tags from https://google.golang.org/grpc/stats?go-get=1 (status code 200)
get "google.golang.org/grpc/stats": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/stats?go-get=1
get "google.golang.org/grpc/stats": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/status?go-get=1
Parsing meta tags from https://google.golang.org/grpc/status?go-get=1 (status code 200)
get "google.golang.org/grpc/status": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/status?go-get=1
get "google.golang.org/grpc/status": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/tap?go-get=1
Parsing meta tags from https://google.golang.org/grpc/tap?go-get=1 (status code 200)
get "google.golang.org/grpc/tap": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/tap?go-get=1
get "google.golang.org/grpc/tap": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/naming?go-get=1
Parsing meta tags from https://google.golang.org/grpc/naming?go-get=1 (status code 200)
get "google.golang.org/grpc/naming": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/naming?go-get=1
get "google.golang.org/grpc/naming": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/resolver/dns?go-get=1
Parsing meta tags from https://google.golang.org/grpc/resolver/dns?go-get=1 (status code 200)
get "google.golang.org/grpc/resolver/dns": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/resolver/dns?go-get=1
get "google.golang.org/grpc/resolver/dns": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc/resolver/passthrough?go-get=1
Parsing meta tags from https://google.golang.org/grpc/resolver/passthrough?go-get=1 (status code 200)
get "google.golang.org/grpc/resolver/passthrough": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/resolver/passthrough?go-get=1
get "google.golang.org/grpc/resolver/passthrough": verifying non-authoritative meta tag
github.com/sirupsen/logrus (download)
Fetching https://golang.org/x/crypto/ssh/terminal?go-get=1
Parsing meta tags from https://golang.org/x/crypto/ssh/terminal?go-get=1 (status code 200)
get "golang.org/x/crypto/ssh/terminal": found meta tag get.metaImport{Prefix:"golang.org/x/crypto", VCS:"git", RepoRoot:"https://go.googlesource.com/crypto"} at https://golang.org/x/crypto/ssh/terminal?go-get=1
get "golang.org/x/crypto/ssh/terminal": verifying non-authoritative meta tag
Fetching https://golang.org/x/crypto?go-get=1
Parsing meta tags from https://golang.org/x/crypto?go-get=1 (status code 200)
golang.org/x/crypto (download)
github.com/grpc-ecosystem/go-grpc-prometheus (download)
github.com/prometheus/client_golang (download)
github.com/beorn7/perks (download)
github.com/prometheus/client_model (download)
github.com/prometheus/common (download)
github.com/matttproud/golang_protobuf_extensions (download)
github.com/prometheus/procfs (download)
github.com/gorilla/websocket (download)
github.com/rs/cors (download)
github.com/mwitkow/go-conntrack (download)
github.com/mwitkow/grpc-proxy (download)
Fetching https://google.golang.org/grpc/transport?go-get=1
Parsing meta tags from https://google.golang.org/grpc/transport?go-get=1 (status code 200)
get "google.golang.org/grpc/transport": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/transport?go-get=1
get "google.golang.org/grpc/transport": verifying non-authoritative meta tag
package google.golang.org/grpc/transport: cannot find package "google.golang.org/grpc/transport" in any of:
	/usr/lib/go-1.10/src/google.golang.org/grpc/transport (from $GOROOT)
	/root/go/src/google.golang.org/grpc/transport (from $GOPATH)
github.com/spf13/pflag (download)
</code>
</details>

**Comment by laSinteZ** [comment] 2018-07-17 07:45
@supapo to be honest, I gave up and just use docker :)

**Comment by mrsmidge** [comment] 2018-08-09 12:14
the root cause appears to be that the transport API has been made internal-only:
https://github.com/grpc/grpc-go/commit/11b582728a13ef54e14e4fa930d693de2e32420f

The commit message suggests that there is a new public transport API coming, and that users of the existing transport API (that they are aware of) should have a preferred alternative.

I'd be keen to know what approach this project plans to take to fix this...

**Comment by mrsmidge** [comment] 2018-08-09 17:26
Ok, a workaround.  Taking inspiration from [some Docker code](https://gitlab.com/snippets/1713665) by @ryanjaeb, we can use `git clone` and `dep` instead of `go get` to make this work:

```
$ cd $GOPATH
$ mkdir src/github.com/improbable-eng
$ cd src/github.com/improbable-eng
$ git clone https://github.com/improbable-eng/grpc-web.git
$ cd grpc-web
$ dep ensure
$ cd go/grpcwebproxy
$ go install
$ echo "w00t!"
```

**Comment by johanbrandhorst** [comment] 2018-09-08 10:45
I gather this is no longer a problem, so I will close this issue. Please shout if it's still happening.

**Closed by johanbrandhorst** 2018-09-08 10:45 UTC

**Comment by mrsmidge** [comment] 2018-09-10 21:18
I believe this is still an open isssue, confirmed on a fresh Ubuntu VM image:

```
$ go get -u github.com/improbable-eng/grpc-web/go/grpcwebproxy
package google.golang.org/grpc/transport: cannot find package "google.golang.org/grpc/transport" in any of:
...
```

`grppcwebproxy` has a dependency on `github.com/mwitkow/grpc-proxy/proxy`, which has a dependency on the no-longer-public `google.golang.org/grpc/transport` in this file: https://github.com/mwitkow/grpc-proxy/blob/master/proxy/handler.go

An issue has already been raised in `grpc-proxy`, although it's a few months old and hasn't been answered: https://github.com/mwitkow/grpc-proxy/issues/30

**Comment by mrsmidge** [comment] 2018-09-11 09:01
@johanbrandhorst - fair point, I agree with you.

Perhaps the installation instructions on `README.md` could be updated to not refer to go-get accordingly?
https://github.com/improbable-eng/grpc-web/blob/master/go/grpcwebproxy/README.md

**Comment by johanbrandhorst** [comment] 2018-09-11 09:18
Good point :). I think this kind of thing was being done with https://github.com/improbable-eng/grpc-web/pull/220, I'll add a comment about pointing to releases.

**Comment by Zmeu213** [comment] 2020-07-09 16:10
@johanbrandhorst i got similar problem here
```
$ go get -v
Fetching https://google.golang.org/grpc/naming?go-get=1
Parsing meta tags from https://google.golang.org/grpc/naming?go-get=1 (status code 200)
get "google.golang.org/grpc/naming": found meta tag get.metaImport{Prefix:"google.golang.org/grpc", VCS:"git", RepoRoot:"https://github.com/grpc/grpc-go"} at https://google.golang.org/grpc/naming?go-get=1
get "google.golang.org/grpc/naming": verifying non-authoritative meta tag
Fetching https://google.golang.org/grpc?go-get=1
Parsing meta tags from https://google.golang.org/grpc?go-get=1 (status code 200)
google.golang.org/grpc (download)
package google.golang.org/grpc/naming: cannot find package "google.golang.org/grpc/naming" in any of:
	/usr/lib/go-1.10/src/google.golang.org/grpc/naming (from $GOROOT)
	/root/gopath/src/google.golang.org/grpc/naming (from $GOPATH)
```
