### ISSUE TITLE
Refused to get unsafe header "grpc-message","grpc-status"

### ISSUE THREAD

**Issue by Dysar** [improbable-eng/grpc-web#486] opened 2019-06-21 06:48 UTC
**Versions of relevant software used**

Errors when making a call to go/grpcwebproxy from Google Chrome saying

```
Refused to get unsafe header "grpc-message"
Refused to get unsafe header "grpc-status"
```

I found [this](https://www.gitmemory.com/mattbailey) saying you can specify CORS access-control-expose-headers
`access-control-expose-headers: grpc-status,grpc-message,x-envoy-upstream-service-time`
and it will work.

And then I saw this line in go/grpcweb/wrapper.go:52 saying
make sure that CORS ExposedHeaders are always empty, otherwise the WebResponse overwrite will not work. 

Is it connected? I was making http call with --allow_all_origins flag in grpcwebproxy set to true.

I changed cors exposed headers to 
`[]string{"grpc-status", "grpc-message", "x-envoy-upstream-service-time"}`
but it did not work.

Thank you in advance!

**Comment by johanbrandhorst** [comment] 2019-06-21 07:48
Dupe of #412 I think?

**Comment by Dysar** [comment] 2019-06-21 07:51
True! thank you

**Closed** 2019-06-21 07:53 UTC
