### ISSUE TITLE
Not receiving cookies in grpc-web specific requests

### ISSUE THREAD

**Issue by shahbazahmed1269** [improbable-eng/grpc-web#217] opened 2018-07-12 10:58 UTC
I am testing GRPC on my Golang server on **localhost** by porting only some of my HTTP/JSON endpoints into GRPC. Below snippet is the setup of GRPC server and on the frontend I am using method: `grpc.unary()` in Typescript to execute the request (as shown in example project).
I am setting a cookie value in one of my HTTP/JSON endpoints. The issue is I am not receiving cookies in HTTP request header in **grpc-web** specific requests but receiving them in my **non-grpc** (HTTP/JSON) requests    (see the code snippet below for details). I also checked and cookie header is not present in `metadata.MD` either.

Am I missing anything or is there a way to get cookies back along with requests originating from **grpc-web**? Any help would be much appreciated. 🙏

```golang
srv := grpc.NewServer()
proto.RegisterMyServiceServer(srv, myService)
wrappedServer := grpcweb.WrapServer(srv)
grpcHandler := func(restHandler http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if wrappedServer.IsAcceptableGrpcCorsRequest(r) ||
			wrappedServer.IsGrpcWebRequest(r) {
                        // Cookie header not present in request here
			wrappedServer.ServeHTTP(w, r)
		} else {
                        // Cookie header present in request here
			restHandler.ServeHTTP(w, r)
		}
	})
}
```

**Comment by jonny-improbable** [comment] 2018-09-04 11:11
Dupe of #103

**Closed by jonny-improbable** 2018-09-04 11:11 UTC
