### ISSUE TITLE
Error not a constructor while calling

### ISSUE THREAD

**Issue by hunnain** [improbable-eng/grpc-web#249] opened 2018-09-21 00:50 UTC
When i call pb file 
import {HelloRequest} from mypbfile'';
const HelloRequest = new HelloRequest();
so there was an error coming in react webpack helloRequest is not a constructor 
please resolve this error.
![screenshot from 2018-09-21 05-47-32](https://user-images.githubusercontent.com/24963356/45854026-44972180-bd62-11e8-95d1-fc56977789a1.png)
![screenshot from 2018-09-21 05-47-02](https://user-images.githubusercontent.com/24963356/45854027-44972180-bd62-11e8-907c-f27d4befd955.png)
![screenshot from 2018-09-21 05-46-54](https://user-images.githubusercontent.com/24963356/45854028-452fb800-bd62-11e8-93a6-3776eddcef55.png)

**Comment by johanbrandhorst** [comment] 2018-09-21 08:29
Hi @hunnain. This is very hard for us to debug. Why don't you start over again from one of our examples? You've got an environmental setup problem here, not a bug. Feel free to join the slack channel as well (https://join.slack.com/t/improbable-eng/shared_invite/enQtMzQ1ODcyMzQ5MjM4LWY5ZWZmNGM2ODc5MmViNmQ3ZTA3ZTY3NzQwOTBlMTkzZmIxZTIxODk0OWU3YjZhNWVlNDU3MDlkZGViZjhkMjc). I'm going to close this as it's not a proper issue report.

**Closed by johanbrandhorst** 2018-09-21 08:29 UTC
