### ISSUE TITLE
base64ResponseWriter.Flush() call itself recursively

### ISSUE THREAD

**Issue by light0x** [improbable-eng/grpc-web#526] opened 2019-08-06 09:24 UTC
**Versions of relevant software used**
0.10.0
**What happened**
![image](https://user-images.githubusercontent.com/1164704/62528121-ea665880-b86e-11e9-9888-96aabd5d27dd.png)

**What you expected to happen**

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**

**Anything else we need to know**

**Comment by johanbrandhorst** [comment] 2019-08-06 09:46
Thanks for the bug report, this was caused by #479. I will back out the change until we can fix this.

**Comment by light0x** [comment] 2019-08-06 09:51
Please tag a new release ASAP, since the bug has broken the whole thing.

**Comment by jonny-improbable** [comment] 2019-08-06 09:59
@light0x we are on it; just waiting for CI to go green.

**Comment by jonny-improbable** [comment] 2019-08-06 11:20
Resolved in release v0.11.0 which has just been published.

**Closed by jonny-improbable** 2019-08-06 11:20 UTC
Labels: bug
