### ISSUE TITLE
undefined: transport.StreamFromContext

### ISSUE THREAD

**Issue by gertcuykens** [improbable-eng/grpc-web#174] opened 2018-04-21 14:39 UTC
```bash
% go get -u github.com/improbable-eng/grpc-web/go/grpcwebproxy
# github.com/mwitkow/grpc-proxy/proxy
go/src/github.com/mwitkow/grpc-proxy/proxy/handler.go:63:30: undefined: transport.StreamFromContext
% 
```

**Comment by johanbrandhorst** [comment] 2018-04-21 14:52
This was removed in a recent commit to grpc-go. See https://github.com/grpc/grpc-go/pull/1904#issuecomment-372087340. Apparently this API should not be used by external packages.

**Comment by easyCZ** [comment] 2018-04-21 16:05
What is the sequence of steps that results in this problem? When building the project, I cannot reproduce the error outlined here.

**Comment by gertcuykens** [comment] 2018-04-21 16:07
Just `go get -u github.com/improbable-eng/grpc-web/go/grpcwebproxy` I think you have the old grpc-go lib already installed?

**Comment by gertcuykens** [comment] 2018-04-21 16:12
Maybe the problem is grpc-go itself and you happen the have the last working version?
```% go get -u github.com/grpc/grpc-go
package github.com/grpc/grpc-go: code in directory /Users/gert/go/src/github.com/grpc/grpc-go expects import "google.golang.org/grpc"
% ```

**Comment by easyCZ** [comment] 2018-04-21 16:29
Reproduced now. Had to delete my existing grpc-web to trigger it. This is a problem in a downstream dependency. Will investigate.

The dependencies of `grpc-web` are vendored so we should be able to use them directly without the impact of the `grpc` change. Cloning the repo directly or using `dep` should work

**Comment by johanbrandhorst** [comment] 2018-04-21 19:53
I think if https://github.com/grpc/grpc-go/issues/2016 gets implemented this should be a fairly straightforward fix.

**Comment by ravihugo** [comment] 2018-04-25 15:53
Is there a work-around or are we pretty much waiting for grpc-go at this point?

**Comment by johanbrandhorst** [comment] 2018-04-27 07:12
https://github.com/grpc/grpc-go/issues/2016 might mean we can incorporate a fix for this here now.

**Comment by pieterlouw** [comment] 2018-05-04 08:26
[grpc-proxy](github.com/mwitkow/grpc-proxy/proxy) requires a small change in it's `handler.go` file to be compatible with the latest `grpc-go`.(There's also a [PR](https://github.com/mwitkow/grpc-proxy/pull/27) for that).   

[proposal]`grpc-proxy` is a small project and dependency - it might be worthwhile merging it into this project as a sub package, for example: `improbable-eng/grpc-web/go/proxy`. (this is what I was basically forced to do with [caddy-grpc](https://github.com/pieterlouw/caddy-grpc) until the PR is merged ). 

By doing that you can change the `handler.go` to be compatible with upstream `grpc-go` by implementing a change similar to the following: https://github.com/pieterlouw/caddy-grpc/blob/master/proxy/handler.go#L69-72

Also, by adding it to this project then it means this project is not dependent on `grpc-proxy`  what appears to be a stale project at the moment.

**Comment by trusktr** [comment] 2018-08-10 22:11
For anyone stumbling on this, this commit perfectly describes how to fix `undefined: transport.StreamFromContext` (or why there's no bin file after go install): https://github.com/jfyne/docker-grpcwebproxy/commit/da712301bde103014e7becbac0fa298384bf622f

For example, I had this problem with http://github.com/improbable-eng/grpc-web, and the following worked:

```js
go get -u github.com/improbable-eng/grpc-web/go/grpcwebproxy
cd $GOPATH/src/github.com/improbable-eng/grpc-web
brew install dep # install golang/dep somehow
dep ensure
go get -u github.com/improbable-eng/grpc-web/go/grpcwebproxy
```

After that `$GOPATH/bin/grpcwebproxy` was available.

**Comment by johanbrandhorst** [comment] 2018-09-08 11:02
It seems this is no longer a problem with the vendored version of gRPC

**Closed by johanbrandhorst** 2018-09-08 11:02 UTC
