### ISSUE TITLE
Crash in vendored gRPC-Go version

### ISSUE THREAD

**Issue by AleksandarFilipov** [improbable-eng/grpc-web#393] opened 2019-04-17 14:04 UTC
**Versions of relevant software used**
/grpcwebproxy-v0.9.1-linux-x86_64

**What happened**
Not able to bridge grpc server with web client, 
after the first call the first part of the log is output, the second call leads to a crash
./grpcwebproxy-v0.9.1-linux-x86_64 --backend_addr=10.251.177.181:50051 --run_tls_server=false --allow_all_origins

**What you expected to happen**
Sweet working grpc-web proxy.

**How to reproduce it (as minimally and precisely as possible)**:
The intention is to replace envoy for some setups in the for the following product. 
Server: https://github.com/volvo-cars/signalbroker-server
Client: https://github.com/volvo-cars/signalbroker-web-client

**Full logs to relevant components**

<details>Logs
<p>

```
./grpcwebproxy-v0.9.1-linux-x86_64 --backend_addr=10.251.177.181:50051 --run_tls_server=false --allow_all_origins --backend_max_call_recv_msg_size=5242880 --use_websockets
INFO[0000] dialing to target with scheme: ""             system=system
INFO[0000] using websockets                             
INFO[0000] ccResolverWrapper: sending new addresses to cc: [{10.251.177.181:50051 0  <nil>}]  system=system
INFO[0000] listening for http on: [::]:8080             
INFO[0000] pickfirstBalancer: HandleSubConnStateChange: 0xc420099680, CONNECTING  system=system
INFO[0000] pickfirstBalancer: HandleSubConnStateChange: 0xc420099680, READY  system=system
INFO[0002] pickfirstBalancer: HandleSubConnStateChange: 0xc420099680, TRANSIENT_FAILURE  system=system
INFO[0002] pickfirstBalancer: HandleSubConnStateChange: 0xc420099680, CONNECTING  system=system
ERRO[0002] finished streaming call                       error="rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR" grpc.code=Internal grpc.method=GetConfiguration grpc.service=base.SystemService grpc.start_time="2019-04-17T15:49:47+02:00" grpc.time_ms=3 span.kind=server system=grpc
INFO[0002] pickfirstBalancer: HandleSubConnStateChange: 0xc420099680, READY  system=system


panic: close of closed channel

goroutine 30 [running]:
github.com/improbable-eng/grpc-web/vendor/google.golang.org/grpc/transport.(*Stream).finish(...)
        /Users/jonny/Projects/grpc-web/src/github.com/improbable-eng/grpc-web/vendor/google.golang.org/grpc/transport/transport.go:400
github.com/improbable-eng/grpc-web/vendor/google.golang.org/grpc/transport.(*http2Client).handleGoAway(0xc420085680, 0xc4201b6f60)
        /Users/jonny/Projects/grpc-web/src/github.com/improbable-eng/grpc-web/vendor/google.golang.org/grpc/transport/http2_client.go:1024 +0x1c6
github.com/improbable-eng/grpc-web/vendor/google.golang.org/grpc/transport.(*http2Client).reader(0xc420085680)
        /Users/jonny/Projects/grpc-web/src/github.com/improbable-eng/grpc-web/vendor/google.golang.org/grpc/transport/http2_client.go:1203 +0x4f1
created by github.com/improbable-eng/grpc-web/vendor/google.golang.org/grpc/transport.newHTTP2Client
        /Users/jonny/Projects/grpc-web/src/github.com/improbable-eng/grpc-web/vendor/google.golang.org/grpc/transport/http2_client.go:272 +0xbf1
```

</p>
</details>

**Anything else we need to know**
Thanks a lot, hope this can be our natural envoy replacer for ARM enviroments.

Server is written in Elixir and uses: https://github.com/elixir-grpc/grpc
Bridging works well using envoy (which we would like to replace for ARM targets)

**Comment by johanbrandhorst** [comment] 2019-04-17 14:11
Wow! This is an interesting error. The crash seems to be in the vendored version of the grpc-go library. First thing would be to establish if this is a known issue and if there is a fix available upstream.

We're using [v1.8.1](https://github.com/improbable-eng/grpc-web/blob/v0.9.1/Gopkg.lock#L280) of gRPC-Go, so it may well be this has been seen and fixed. The latest release of gRPC is [v1.20.0](https://github.com/grpc/grpc-go/releases/tag/v1.20.0).

This would be a great reason to usher along https://github.com/improbable-eng/grpc-web/issues/236. Would you be interested submitting a pull request with updated dependencies?

**Comment by johanbrandhorst** [comment] 2019-04-17 14:12
FYI: You probably don't want to link to your internal gitlab server in this issue. It's hidden behind a sign-in screen anyway, so it doesn't add much.

**Comment by johanbrandhorst** [comment] 2019-04-17 14:20
A quick search through the grpc-go issue tracker didn't find this exact issue, but I still think it'll be worth to just upgrade the gRPC-Go dependency and then try to reproduce the error. It will have changed a _lot_ since 1.8.

**Comment by AleksandarFilipov** [comment] 2019-04-17 14:47
Sound like an adventure, I guess I need to get familiar with golang sooner or later, this could be that oppertunity ;)

**Comment by johanbrandhorst** [comment] 2019-04-17 14:48
:cold_sweat: if you have no experience with Go this might be a bit annoying. Please let me know if you need any assistance. Go dependency management can be painful for beginners.

**Comment by AleksandarFilipov** [comment] 2019-04-17 14:51
Well in that case I'll let you know that I need help in a few days ;)

**Comment by johanbrandhorst** [comment] 2019-04-17 14:52
If you need debugging help; remember [![Slack](https://img.shields.io/badge/join%20slack-%23grpc--web-brightgreen.svg)](https://join.slack.com/t/improbable-eng/shared_invite/enQtMzQ1ODcyMzQ5MjM4LWY5ZWZmNGM2ODc5MmViNmQ3ZTA3ZTY3NzQwOTBlMTkzZmIxZTIxODk0OWU3YjZhNWVlNDU3MDlkZGViZjhkMjc). Alternatively the gophers slack #grpc channel would also work.

**Comment by johanbrandhorst** [comment] 2019-04-19 08:54
I took the liberty of updating the dependencies myself. If you'd like to, you can try a new version of the grpcwebproxy built from #395:
[grpcwebproxy-alpha-linux-x86_64.zip](https://github.com/improbable-eng/grpc-web/files/3097579/grpcwebproxy-alpha-linux-x86_64.zip). Let me know if this fixes the problem.

**Comment by AleksandarFilipov** [comment] 2019-04-19 11:23
;) I'll try to test it in the coming days. I gave it an hour the other night, didn't even manage to get the deps tool up an running...

**Comment by AleksandarFilipov** [comment] 2019-04-21 12:48
Just tested the new version ;(. It doesn't crash like before, however it still doesn't work. Would you say that my flags make sense? 

```
grpc-web-golang/alpha $ ./grpcwebproxy-alpha-linux-x86_64 --backend_addr=127.0.0.1:50051 --run_tls_server=false --allow_all_origins --server_http_debug_port 8081
INFO[0000] parsed scheme: ""                             system=system
INFO[0000] scheme "" not registered, fallback to default scheme  system=system
INFO[0000] ccResolverWrapper: sending update to cc: {[{127.0.0.1:50051 0  <nil>}] }  system=system
INFO[0000] ClientConn switching balancer to "pick_first"  system=system
INFO[0000] pickfirstBalancer: HandleSubConnStateChange: 0xc00006a5a0, CONNECTING  system=system
INFO[0000] listening for http on: [::]:8081             
INFO[0000] pickfirstBalancer: HandleSubConnStateChange: 0xc00006a5a0, READY  system=system


INFO[0035] transport: loopyWriter.run returning. connection error: desc = "transport is closing"  system=system
ERRO[0035] finished streaming call with code Internal    error="rpc error: code = Internal desc = stream terminated by RST_STREAM with error code: PROTOCOL_ERROR" grpc.code=Internal grpc.method=GetConfiguration grpc.service=base.SystemService grpc.start_time="2019-04-21T14:44:52+02:00" grpc.time_ms=0.699 span.kind=server system=grpc
INFO[0035] pickfirstBalancer: HandleSubConnStateChange: 0xc00006a5a0, TRANSIENT_FAILURE  system=system
INFO[0035] pickfirstBalancer: HandleSubConnStateChange: 0xc00006a5a0, CONNECTING  system=system
INFO[0035] pickfirstBalancer: HandleSubConnStateChange: 0xc00006a5a0, READY  system=system
```

**Comment by johanbrandhorst** [comment] 2019-04-21 13:40
Great to hear the crash is fixed, that should allow us to close this issue.

As for your new problem, the logs indicate that your proxy is able to connect to the server (the `READY` message confirms that). The error you're getting implies that your connection was unexpectedly dropped. In the past when I've seen this kind of thing it's been because some intermediary (another proxy, load balancer) has dropped the underlying TCP connection. This could be happening in your case too. Inspect your infrastructure setup and ensure all hops between your grpcwebproxy and the server are http/2 compatible and don't drop connections. Also investigate whether some custom keepalive setting help. I think that is configurable in the proxy.

**Comment by AleksandarFilipov** [comment] 2019-04-21 13:56
Both client/server runs on the same machine, so the test setup is fairly simple (feel free to try it :). It also works well with envoy (which we intend to replace). I'll check if there is a keepalive config which I can pass to your binary. Thanks for your middle easter response.

**Comment by johanbrandhorst** [comment] 2019-04-21 14:03
Hm, for a local connection this is a strange error. Have you got your application logs? What is the logic in GetConfiguration doing?

**Comment by AleksandarFilipov** [comment] 2019-04-21 14:59
https://github.com/volvo-cars/signalbroker-server/tree/master/apps/grpc_service/proto_files the system file contains the getcofiguration. The server logs were quiet, for the client i'm not sure. Not by a computer right now. The getconfig is fairly simple. The following calls (once we get there) are heavier.

**Comment by AleksandarFilipov** [comment] 2019-04-21 20:21
client reports, probably as you expected
```
Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
```

**Comment by johanbrandhorst** [comment] 2019-04-22 08:44
The problem lies between the proxy and the server, as far as I can tell. I would encourage you to raise an issue with the grpc-go project, they will be able to help you debug it better than I can. I will close this issue once the PR has been merged as it appears the crash has been fixed. Sorry I can't be of more help.

**Comment by AleksandarFilipov** [comment] 2019-04-23 06:30
Ok thanks for your help. Just for my understanding; I know we have go clients communicating with the grpc server. I would assume they are using the same grpc-go library. Does that make sense?

**Comment by johanbrandhorst** [comment] 2019-04-23 06:50
Yes, they grpcwebproxy you're using is just a gRPC client wrapped in a custom gRPC-Web translation middleware. The READY logs come from the grpc-go client library.

**Comment by AleksandarFilipov** [comment] 2019-05-03 11:28
@johanbrandhorst, I'm a little hesitant to open issues the grpc-go client because we have other go clients that work as expected. Please share your thought on this. Thanks!

**Comment by johanbrandhorst** [comment] 2019-05-03 11:31
I'm not sure what could be causing this error on our side. If you could produce a minimal example that anyone could use to reproduce the error we could dig into it more, but I personally won't have time to debug this.

**Comment by AleksandarFilipov** [comment] 2019-05-08 21:17
Thanks you for you reply, just like you I'm crazy busy. I'll ping you if i have further updates (minimal example).

**Closed** 2019-06-13 13:29 UTC
